---

# Install LXC
- name: install packages
  apt: name={{ item }} state=present force=yes
  tags: lxc
  with_items:
    - lxc
    - bridge-utils
    - debootstrap
    - git
    - git-core
    - dnsmasq
    - dnsmasq-utils
    - kexec-tools

# Install latest kernel image from backports
- name: install backport kernel
  apt: name=linux-image-amd64 state=latest default_release=wheezy-backports force=yes

- stat: path=/usr/share/lxc/templates/lxc-debian-wheezy
  register: lxc_template_absent

- name: copy better squeeze template
  copy: src=lxc-debian-0.9.0-upstream-squeeze dest=/usr/share/lxc/templates/lxc-debian-squeeze owner=root group=root mode=0755
  when: lxc_template_absent|success

- name: copy better wheezy template
  copy: src=lxc-debian-0.9.0-upstream-wheezy dest=/usr/share/lxc/templates/lxc-debian-wheezy owner=root group=root mode=0755
  when: lxc_template_absent|success

# Grub
- lineinfile: dest=/etc/default/grub regexp='^GRUB_CMDLINE_LINUX_DEFAULT' line='GRUB_CMDLINE_LINUX_DEFAULT="quiet cgroup_enable=memory swapaccount=1"' backup=yes
  notify: update grub

# Mount cgroup+fstab
- mount: src=cgroup name='/sys/fs/cgroup' opts=defaults fstype=cgroup state=mounted

# network interface bridge
- name: configure network bridge interfaces
  template: src=interfaces_bridge.j2 dest=/etc/network/interfaces backup=yes
  when: lxc_network_mode == "bridge"
  notify: restart network

# network interface nat
- name: configure network nat interfaces
  template: src=interfaces_nat.j2 dest=/etc/network/interfaces backup=yes
  when: lxc_network_mode == "nat"
  notify: restart network

# check /var/lib/lxc
- name: Check if path exists
  stat: path=/var/lib/lxc
  register: check_path

# create the lxc directory /home/lxc
- name: create the lxc directory
  command: mv /var/lib/lxc /home
  when: check_path.stat.isdir
  
# check /var/lib/lxc
- name: Check if path exists
  stat: path=/var/lib/lxc
  register: check_path

# link to lxc directory
- name: link to lxc directory
  file: src=/home/lxc dest=/var/lib/lxc owner=root group=root state=link
  when: not check_path.stat.exists

# Dnsmasq
- name: configure dnsmasq
  template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.conf owner=root group=root mode=0644

